### ISSUE TITLE
rollup-plugin-multi-entry throws error when using --watch

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [bahmutov/rollem#24]
I created a simple example, where I'm trying to give multiple entries to rollem with the [multi-entry rollup plugin](https://github.com/rollup/rollup-plugin-multi-entry). See the attached [rollemtest.zip](https://github.com/bahmutov/rollem/files/739393/rollemtest.zip) for the source.

If I execute `rollem -c rollup.config.js`, then it works fine. If on the other hand I try executing `rollem -cw rollup.config.js`, it throws the following error (assuming, that I'm standing in the C:\wamp\www\rolluptest\ folder):

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at join (path.js:466:7)
    at Object.<anonymous> (C:\wamp\www\rolluptest\node_modules\rollem\bin\rollem.js:11:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
```

If I replace rollem with rollup (version 0.41.4), then both codes work without a problem.
See [rolluptest.zip](https://github.com/bahmutov/rollem/files/739434/rolluptest.zip) for this other case.

**Comment by meszaros-lajos-gyorgy** [comment]
Correction: the above error is produced with the -w switch. Using the --watch will produce this error:

```
Treating 'rollup-plugin-multi-entry' as external dependency
{ AssertionError: expected list of configs
    at Console.assert (console.js:95:23)
    at rollem (C:\wamp\www\rolluptest\node_modules\rollem\src\index.js:45:11)
    at C:\wamp\www\rolluptest\node_modules\rollem\bin\rollem.js:36:3
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'expected list of configs',
  generatedMessage: false }
```

**Comment by meszaros-lajos-gyorgy** [comment]
**Correction**: the above error was produced with the -cw switch. Using the --watch will produce the following error:

```
Treating 'rollup-plugin-multi-entry' as external dependency
TypeError: Path must be a string. Received [ 'src/a.js', 'src/b.js' ]
    at assertPath (path.js:7:11)
    at dirname (path.js:697:5)
    at _map (C:\wamp\www\rolluptest\node_modules\ramda\dist\ramda.js:262:27)
    at map (C:\wamp\www\rolluptest\node_modules\ramda\dist\ramda.js:5959:20)
    at C:\wamp\www\rolluptest\node_modules\ramda\dist\ramda.js:586:23
    at Object.f2 [as map] (C:\wamp\www\rolluptest\node_modules\ramda\dist\ramda.js:473:22)
    at mergeWatchedFolders (C:\wamp\www\rolluptest\node_modules\rollem\src\merge-folders.js:16:21)
    at collectInputFolders (C:\wamp\www\rolluptest\node_modules\rollem\src\index.js:36:10)
    at rollem (C:\wamp\www\rolluptest\node_modules\rollem\src\index.js:48:21)
    at C:\wamp\www\rolluptest\node_modules\rollem\bin\rollem.js:36:3
```

**Comment by meszaros-lajos-gyorgy** [comment]
This issue has been fixed with the release of 1.10. Closing issue.

**Comment by ghost** [comment]
Sorry, I has encountered this issue since a week ago
When i run `rollem -c`

![image](https://cloud.githubusercontent.com/assets/8049878/25031801/006a53fe-2102-11e7-9c8c-d5065a9a5cbe.png)

package.json devDependencies and dependencies

[here is package.json link](https://gist.github.com/liuliangsir/cd2751e81b52cefefa0141e6d8aa7799)

[here is .babelrc link](https://gist.github.com/liuliangsir/88b0818ee3fd6468da480c8def42b083)

look forward to your reply

**Comment by meszaros-lajos-gyorgy** [comment]
You didn't specify a config filename for rollup to parse. If you use the -c switch, then it expects another parameter after it, which would refer to the filename:

https://github.com/bahmutov/rollem#install-and-use

We could add a proper error message saying, that the configuration is invalid, but that is a different topic.

For the record, this part throws the error: https://github.com/bahmutov/rollem/blob/master/bin/rollem.js#L11

argv.c is set, so it returns true.

Changing line 7 to this should "fix" the unexpected error:

```const argv = require('minimist')(process.argv.slice(2), {string: 'c'})```

**Comment by meszaros-lajos-gyorgy** [comment]
This issue have already been reported in #19, followups should be discussed there.

**Comment by ghost** [comment]
thx~
